name: Deploy

on:
  push:
    branches:
      - main # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "passaver-v2" #Must be unique in Heroku
          heroku_email: "theleoralph@gmail.com"
          procfile: "web: vendor/bin/heroku-php-apache2 public/"